### ISSUE TITLE
好像不生效

### ISSUE THREAD

**Issue by kasougrey** [vm0100/wepy-plugin-vant#1]
按你的操作步骤，好像不生效。一样的步骤 wepy-plugin-iview就是有效的

**Comment by johnnylj** [comment]
需要先安装一个typescript编译器
npm install wepy-compiler-typescript
再执行build

**Comment by vm0100** [comment]
如果最后module.exports.plugins中存在vant的话应该是有效的，不生效的话 把components里面的vant删掉 然后把dist删掉 然后run一下看看
